### ISSUE TITLE
Migrate prod data to use new reason codes

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/model-sales-val#126]
Once https://github.com/ccao-data/model-sales-val/issues/125 is complete, we should migrate our prod flags to use the new scheme for reason codes so that our data is consistent. We can use the `ccao-data-warehouse-sale-backup-us-east-1` again to back up the old flags before the migration.

**Comment by wagnerlmichael** [comment]
Completed here https://github.com/ccao-data/model-sales-val/commit/8674745df4e9e8da0edef6bc5ab1e7e0fbbc3779

**Comment by wagnerlmichael** [comment]
Completed here https://github.com/ccao-data/model-sales-val/commit/8674745df4e9e8da0edef6bc5ab1e7e0fbbc3779
