### ISSUE TITLE
Investigate using lines 8 and 9 of PTAX-203 form for sales validation

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/model-sales-val#77]
The [PTAX-203](https://tax.illinois.gov/content/dam/soi/en/web/tax/localgovernments/property/documents/ptax-203.pdf) records information related to property transfers in Illinois. This repository currently uses a subset of answers from Question 10 on the form (combined with statistical flagging) to flag sales as non-arms-length.

We're interested in expanding the PTAX-203 information used for flagging to include Questions 8 and 9, which cover primary use and improvements.

We need to perform some preliminary exploratory data analysis (EDA) to figure out how many additional sales get flagged when using these questions.

The Q9 and Q10 data can be found in the `sale.mydec` table in Athena. The output of this issue should be a simple Quarto doc that queries data from Athena and outputs counts of flags by year, as well as some examples of the flagged sales. Work with @wagnerlmichael to get started.

**Comment by wagnerlmichael** [comment]
For now we are going to table this until after modeling, but it seems like the following scenarios could be useful to add

- Question 9 
- Mismatch in Q8 between current use and intended use

**Comment by wagnerlmichael** [comment]
Closing this as this work has largely been completed.

https://github.com/ccao-data/enterprise-intelligence/pull/172
