### ISSUE TITLE
Make flagging script more flexible with respect to geography

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/model-sales-val#98]
Two new requirements that both require a more flexible approach to geography:

1. We would like to be able to run a flagging job against sales within an arbitrary geography or set of geographies (e.g. flag sales within a tri, municipality, or group of neighborhoods)
2. We would like to be able to group sales by arbitrary sets of geographies (e.g. a municipality or a group of neighborhoods)

I am assuming that we don't need to support multiple types of geography per run (e.g. we _do_ need to allow a user to decide between running a flagging job on a tri or a municipality; but we _don't_ need to allow a user to run a flagging job on both a tri _and_ a municipality in the same run).

This will require changes to at least the following parts of the code:

* The query in the flagging script(s)
* The config parameters in `input.yaml`
* The `parameter` output table

Depending on the degree of changes required by the design for this feature, it may be worth sketching out a proposed solution in writing for approval before getting started on the implementation.

**Comment by wagnerlmichael** [comment]
(In progress)

While discussing potential data models with @jeancochrane, we identified assumptions which, if violated, would make the data model significantly more complicated for the user.
